-- Frozen schema from thailand_flood_intelligence_implementation_data_manifest.md
CREATE TYPE semantic_status AS ENUM ('VERIFIED','PARTIAL','UNVERIFIED');

CREATE TYPE quality_state AS ENUM (
  'VALID','VALID_ZERO','MISSING','STALE','SUSPECT',
  'NOT_SUPPORTED','SOURCE_ERROR','ESTIMATED','NOT_CONFIGURED'
);

CREATE TYPE observation_type AS ENUM (
  'OBSERVED','DERIVED','FORECAST','ESTIMATED',
  'CONFIRMED_IMPACT','OFFICIAL_WARNING'
);

CREATE TYPE hazard_type AS ENUM (
  'RIVER_OVERFLOW','FLASH_FLOOD','LOCAL_RAIN','COASTAL_TIDAL','COMPOUND'
);

CREATE TYPE network_node_type AS ENUM (
  'SOURCE','CATCHMENT','SUBCATCHMENT','HEADWATER','GAUGE',
  'JUNCTION','CONFLUENCE','RESERVOIR','DIVERSION','GATE','PUMP',
  'CANAL_CONNECTION','TIDE_BOUNDARY','OUTLET','FLOODPLAIN_STORAGE'
);

CREATE TYPE network_edge_type AS ENUM (
  'RIVER_REACH','CREEK','CANAL','CONTROLLED_CANAL','DIVERSION',
  'GATE_PATH','PUMP_PATH','FLOODPLAIN_CONNECTION','ESTUARY'
);

CREATE TYPE edge_direction_type AS ENUM (
  'FORWARD','REVERSE','BIDIRECTIONAL','CONTROLLED','DYNAMIC'
);

CREATE TYPE boundary_type AS ENUM (
  'SEA','TIDAL_RIVER','RIVER','LAKE','RESERVOIR','CONTROLLED_CANAL','UNKNOWN'
);

CREATE TYPE bank_reference_type AS ENUM (
  'SURVEYED_BANK','OFFICIAL_STATION_BANK','LEVEE_CREST',
  'OPERATIONAL_CRITICAL_LEVEL','HISTORICAL_BANKFULL','DEM_ESTIMATE'
);

CREATE TYPE event_state AS ENUM (
  'GENERATING','HEADWATER_ROUTING','TRIBUTARY_ROUTING',
  'MAIN_RIVER_ROUTING','FLOODPLAIN_FILLING','RECESSION','ENDED'
);

CREATE TYPE wave_state AS ENUM (
  'FORECAST','GENERATING','IN_TRANSIT','ARRIVING','PASSING','PASSED','DISSIPATED'
);

CREATE TYPE floodplain_state_type AS ENUM (
  'DRY','FILLING','CONNECTED','DRAINING','ISOLATED_PONDING'
);

CREATE TYPE confidence_level AS ENUM ('HIGH','MEDIUM','LOW','UNAVAILABLE');
